export const COMMANDS={
VARIABLES:[["setvar","Set bot variables remotely","setvar MY_VAR=some_value"],["getvar","Get a bot variable","getvar MY_VAR"],["delvar","Delete a bot variable","delvar MY_VAR"],["setenv","Set a bot configuration variable","setenv MY_VAR=some_value"],["delsudo","Delete sudo access","delsudo"],["afk","Set, check or list AFK status","afk [reason] | afk | afk list"],["autodl","Auto-download URL watcher","autodl on|off|groups|dms|status"],["chatbot","AI chatbot management","chatbot on|off|groups|dms|set|clear"],["ai","Ask Gemini AI","ai <question>"],["info","Show command information","info <command>"],["alive","Check whether the bot is alive","alive"],["setalive","Set the alive message","setalive <message> | setalive help"],["games","List available games","games"],["gif","Convert video to GIF","gif"],["rotate","Rotate video left/right","rotate left|right"],["flip","Flip video","flip"],["mention","Auto mention reply management","mention set|get|del|help"],["delete","Delete a message for everyone","delete"]],
OWNER:[["allvar","Show all bot variables","allvar"],["settings","Show bot settings","settings"],["setsudo","Add sudo access","setsudo"],["getsudo","List sudo users","getsudo"],["callreject","Manage call rejection","callreject on|off|allow|remove|list|clear|msg|msg off"],["install","Install an external plugin","install <plugin>"],["plugin","Show installed plugins","plugin"],["remove","Remove a plugin","remove <plugin>"],["pupdate","Update a plugin","pupdate <plugin_name>"],["block","Block a user","block @user | reply"],["join","Join a group by invite link","join <invite-link>"],["unblock","Unblock a user","unblock @user | reply"],["pp","Change/get profile picture","pp"],["gpp","Change/get group icon","gpp"],["update","Check/apply bot updates","update"]],
SETTINGS:[["platform","Show platform information","platform"],["language","Set bot language","language"],["mode","Set public/private mode","mode public|private"],["antidelete","Manage anti-delete","antidelete on|off"],["setinfo","Set bot info","setinfo <text>"],["setname","Set bot name","setname <name>"],["setowner","Set owner","setowner <number>"],["setimage","Set bot image","setimage"]],
GROUP:[["toggle","Toggle commands","toggle img"],["antibot","Detect and remove other bots","antibot on|off"],["antispam","Detect and remove spam","antispam on|off"],["pdm","Promote/demote alert","pdm on|off"],["antidemote","Auto-promote demoted member and demote actor","antidemote on|off"],["antipromote","Auto-demote promoted member and demote promoter","antipromote on|off"],["antilink","Advanced link protection","antilink warn|kick|delete|off"],["antiword","Kick members using disallowed words","antiword"],["automute","Automatic IST-based mute","automute"],["autounmute","Automatic IST-based unmute","autounmute"],["getmute","Show mute schedule","getmute"],["antifake","Block configured fake numbers","antifake"],["kick","Kick mentioned/replied/all/prefix members","kick @user | kick all | kick 91"],["add","Add a group member","add <number>"],["promote","Promote a member","promote @user"],["requests","Manage pending join requests","requests approve|reject|all"],["leave","Leave the group","leave"],["quoted","Recover the replied quoted message","quoted"],["demote","Demote a member","demote @user"],["mute","Mute a group indefinitely or for duration","mute | mute 1h | mute 5m"],["unmute","Unmute the group","unmute"],["jid","Show JID","jid"],["invite","Get group invite","invite"],["revoke","Revoke group invite","revoke"],["glock","Lock group settings","glock"],["gunlock","Unlock group settings","gunlock"],["gname","Change group name","gname <name>"],["gdesc","Change group description","gdesc <text>"],["common","Find common participants in two groups","common <group-jid>"],["tag","Tag a member/group","tag @user"],["tagall","Tag all members","tagall"],["tagadmin","Tag all admins","tagadmin"],["gstatus","Update group status","gstatus <text>|reply media"],["msgs","Show message counts","msgs"],["inactive","Show/kick inactive members","inactive [kick]"],["warn","Warn a member","warn @user"],["warnings","Show member warnings","warnings @user"],["rmwarn","Remove a warning","rmwarn @user"],["resetwarn","Reset warnings","resetwarn @user"],["warnlist","List warning records","warnlist"],["setwarnlimit","Set warning limit","setwarnlimit <number>"],["warnstats","Show warning statistics","warnstats"],["welcome","Manage welcome messages","welcome on|off|get|del"],["goodbye","Manage goodbye messages","goodbye on|off|get|del"],["testwelcome","Test welcome message","testwelcome"],["testgoodbye","Test goodbye message","testgoodbye"]],
UTILITY:[["uptime","Show bot uptime","uptime"],["menu","Show the full command menu","menu"],["testalive","Test alive message","testalive"],["attp","Convert text to animated sticker","attp <text>"],["tts","Google text-to-speech","tts <text>"],["upload","Upload a URL as document","upload <url>"],["fancy","Generate fancy text","fancy <text>"],["filter","Create an auto-reply filter","filter trigger | response | scope | options"],["filters","List filters","filters"],["delfilter","Delete a filter","delfilter <trigger>"],["togglefilter","Enable/disable a filter","togglefilter <trigger>"],["testfilter","Test a filter","testfilter <text>"],["filterhelp","Show filter help","filterhelp"],["stickcmd","Attach a command to a sticker","stickcmd <command>"],["unstick","Remove a sticker command","unstick"],["getstick","Get sticker command","getstick"],["diff","Show participant difference between groups","diff <group-jid>"],["getjids","List group JIDs","getjids [all|recent] [count]"],["users","Show top users by message count","users [count]"],["schedule","Schedule a command/message","schedule <time> <text>"],["scheduled","List scheduled jobs","scheduled"],["cancel","Cancel a scheduled job","cancel <id>"],["age","Calculate age","age <date>"],["cntd","Countdown","cntd <date/time>"],["ping","Check latency","ping"],["vv","Handle view-once media","vv"]],
SEARCH:[["img","Search Google Images and send results","img <query>"],["find","Find music name using AI","find (reply to music)"]],
EDIT:[["sticker","Convert media to sticker","sticker"],["mp3","Convert video to MP3","mp3"],["slow","Slow media","slow"],["sped","Speed up media","sped"],["bass","Adjust bass","bass"],["photo","Extract photo from media","photo"],["doc","Convert media to document","doc"],["square","Make media square","square"],["resize","Resize media","resize 16:9|9:16|4:3|21:9"],["compress","Compress media","compress <percent>"],["trim","Trim media","trim"],["black","Create black-background media","black"],["avmix","Mix audio/video","avmix"],["vmix","Mix video/media","vmix"],["slowmo","Create slow motion","slowmo"],["circle","Make circular media","circle"],["interp","Interpolate media","interp"],["take","Take/extract media","take"],["mp4","Convert media to MP4","mp4"],["url","Get media URL","url"]],
MISC:[["clear","Clear bot data","clear"],["retry","Retry the last operation","retry"]],
CONVERTERS:[["pdf","Convert media/text to PDF","pdf"]],
SYSTEM:[["restart","Restart the bot process","restart"]],
DOWNLOAD:[["insta","Instagram post/reel/tv/highlights downloader","insta <url>"],["fb","Facebook video downloader","fb <url>"],["story","Instagram stories downloader","story <url>"],["pinterest","Pinterest downloader","pinterest <url>"],["tiktok","TikTok video downloader","tiktok <url>"],["song","Search YouTube and download audio","song <query>"],["yts","Search YouTube with detailed info","yts <query>"],["ytv","Download YouTube video with quality selection","ytv <url>"],["video","Download YouTube video at 360p","video <url>"],["yta","Download YouTube audio as document","yta <url>"],["play","Play audio from YouTube search/link","play <query|url>"],["spotify","Download audio from Spotify link","spotify <url>"]],
WHATSAPP:[["react","React to a message","react <emoji>"],["edit","Edit a sent message","edit <text>"],["send","Forward a replied message to a JID","send <jid>"],["forward","Forward a replied message to a JID","forward <jid>"]]
};
export const COMMAND_ALIASES={h:"menu",help:"menu",commands:"menu",setv:"setvar",getv:"getvar",delv:"delvar"};
export function allCommands(){return Object.entries(COMMANDS).flatMap(([category,items])=>items.map(([name,description,usage])=>({category,name,description,usage})))}
